import type { UiStrings } from '../types'

const da: UiStrings = {
  locale: 'da-DK',
  languageLabel: 'Sprog',
  languageSelectAriaLabel: 'Valg af sprog',
  darkModeLabel: 'Mork tilstand',
  darkModeLegend: 'Mork tilstand',
  darkModeSelectionAriaLabel: 'Valg af mork tilstand',
  offLabel: 'Fra',
  onLabel: 'Til',
  appTitle: 'Aspire Starter',
  appSubtitle: 'Moderne udvikling af distribuerede applikationer',
  aspireLogoAltText: 'Aspire logo',
  visitAspireWebsiteAriaLabel: 'Besog Aspires hjemmeside (abner i en ny fane)',
  languageOptionEnglish: 'Engelsk',
  languageOptionDanish: 'Dansk',
  languageOptionFinnish: 'Finsk',
  weatherHeading: 'Vejrudsigt',
  temperatureUnitLegend: 'Temperaturenhed',
  temperatureUnitAriaLabel: 'Valg af temperaturenhed',
  fahrenheitHiddenLabel: 'Fahrenheit',
  celsiusHiddenLabel: 'Celsius',
  loadingLabel: 'Indlaeser...',
  refreshLabel: 'Opdater',
  loadingWeatherAriaLabel: 'Indlaeser vejrudsigt',
  refreshWeatherAriaLabel: 'Opdater vejrudsigt',
  loadingWeatherDataAriaLabel: 'Indlaeser vejrdata',
  loadingWeatherDataText: 'Indlaeser data til vejrudsigt...',
  footerNavigationAriaLabel: 'Sidefodsnavigation',
  learnMoreAspire: 'Laer mere om Aspire',
  opensInNewTab: '(abner i en ny fane)',
  githubAriaLabel: 'Vis Aspire pa GitHub (abner i en ny fane)',
  githubHiddenLabel: 'GitHub',
  weatherForDateAriaLabel: (dateLabel) => `Vejr for ${dateLabel}`,
  temperatureAriaLabel: (temperature, unit) => `Temperatur: ${temperature} grader ${unit === 'celsius' ? 'Celsius' : 'Fahrenheit'}`,
  httpErrorLabel: (status) => `Kunne ikke hente vejrdata (HTTP ${status}).`,
  fetchErrorLabel: 'Kunne ikke hente vejrdata.',
  weatherSummaries: {
    freezing: 'Frysende',
    bracing: 'Bidskoldt',
    chilly: 'Koligt',
    cool: 'Svalt',
    mild: 'Mildt',
    warm: 'Lunt',
    balmy: 'Behageligt',
    hot: 'Varmt',
    sweltering: 'Hede',
    scorching: 'Stegende',
  },
}

export default da
