import type { UiStrings } from '../types'

const en: UiStrings = {
  locale: 'en-US',
  languageLabel: 'Language',
  languageSelectAriaLabel: 'Language selection',
  darkModeLabel: 'Dark mode',
  darkModeLegend: 'Dark mode',
  darkModeSelectionAriaLabel: 'Dark mode selection',
  offLabel: 'Off',
  onLabel: 'On',
  appTitle: 'Aspire Starter',
  appSubtitle: 'Modern distributed application development',
  aspireLogoAltText: 'Aspire logo',
  visitAspireWebsiteAriaLabel: 'Visit Aspire website (opens in new tab)',
  languageOptionEnglish: 'English',
  languageOptionDanish: 'Danish',
  languageOptionFinnish: 'Finnish',
  weatherHeading: 'Weather Forecast',
  temperatureUnitLegend: 'Temperature unit',
  temperatureUnitAriaLabel: 'Temperature unit selection',
  fahrenheitHiddenLabel: 'Fahrenheit',
  celsiusHiddenLabel: 'Celsius',
  loadingLabel: 'Loading...',
  refreshLabel: 'Refresh',
  loadingWeatherAriaLabel: 'Loading weather forecast',
  refreshWeatherAriaLabel: 'Refresh weather forecast',
  loadingWeatherDataAriaLabel: 'Loading weather data',
  loadingWeatherDataText: 'Loading weather forecast data...',
  footerNavigationAriaLabel: 'Footer navigation',
  learnMoreAspire: 'Learn more about Aspire',
  opensInNewTab: '(opens in new tab)',
  githubAriaLabel: 'View Aspire on GitHub (opens in new tab)',
  githubHiddenLabel: 'GitHub',
  weatherForDateAriaLabel: (dateLabel) => `Weather for ${dateLabel}`,
  temperatureAriaLabel: (temperature, unit) => `Temperature: ${temperature} degrees ${unit === 'celsius' ? 'Celsius' : 'Fahrenheit'}`,
  httpErrorLabel: (status) => `Failed to fetch weather data (HTTP ${status}).`,
  fetchErrorLabel: 'Failed to fetch weather data.',
  weatherSummaries: {
    freezing: 'Freezing',
    bracing: 'Bracing',
    chilly: 'Chilly',
    cool: 'Cool',
    mild: 'Mild',
    warm: 'Warm',
    balmy: 'Balmy',
    hot: 'Hot',
    sweltering: 'Sweltering',
    scorching: 'Scorching',
  },
}

export default en
