import type { UiStrings } from '../types'

const fi: UiStrings = {
  locale: 'fi-FI',
  languageLabel: 'Kieli',
  languageSelectAriaLabel: 'Kielen valinta',
  darkModeLabel: 'Tumma tila',
  darkModeLegend: 'Tumma tila',
  darkModeSelectionAriaLabel: 'Tumman tilan valinta',
  offLabel: 'Pois',
  onLabel: 'Paalla',
  appTitle: 'Aspire Starter',
  appSubtitle: 'Nykyaikainen hajautettujen sovellusten kehitys',
  aspireLogoAltText: 'Aspire-logo',
  visitAspireWebsiteAriaLabel: 'Avaa Aspire-verkkosivusto (avautuu uuteen valilehteen)',
  languageOptionEnglish: 'Englanti',
  languageOptionDanish: 'Tanska',
  languageOptionFinnish: 'Suomi',
  weatherHeading: 'Saaennuste',
  temperatureUnitLegend: 'Lampotilayksikko',
  temperatureUnitAriaLabel: 'Lampotilayksikon valinta',
  fahrenheitHiddenLabel: 'Fahrenheit',
  celsiusHiddenLabel: 'Celsius',
  loadingLabel: 'Ladataan...',
  refreshLabel: 'Paivita',
  loadingWeatherAriaLabel: 'Ladataan saaennustetta',
  refreshWeatherAriaLabel: 'Paivita saaennuste',
  loadingWeatherDataAriaLabel: 'Ladataan saadataa',
  loadingWeatherDataText: 'Ladataan saaennustedataa...',
  footerNavigationAriaLabel: 'Alatunnisteen navigointi',
  learnMoreAspire: 'Lue lisaa Aspiresta',
  opensInNewTab: '(avautuu uuteen valilehteen)',
  githubAriaLabel: 'Nayta Aspire GitHubissa (avautuu uuteen valilehteen)',
  githubHiddenLabel: 'GitHub',
  weatherForDateAriaLabel: (dateLabel) => `Saa paivalle ${dateLabel}`,
  temperatureAriaLabel: (temperature, unit) => `Lampotila: ${temperature} astetta ${unit === 'celsius' ? 'Celsius' : 'Fahrenheit'}`,
  httpErrorLabel: (status) => `Saadatan haku epaonnistui (HTTP ${status}).`,
  fetchErrorLabel: 'Saadatan haku epaonnistui.',
  weatherSummaries: {
    freezing: 'Jaatava',
    bracing: 'Viilea',
    chilly: 'Kolea',
    cool: 'Viileahko',
    mild: 'Leuto',
    warm: 'Lamminta',
    balmy: 'Miellyttava',
    hot: 'Kuuma',
    sweltering: 'Tukala',
    scorching: 'Polttava',
  },
}

export default fi
